import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Drobotij Leandro Nahuel',
  description: 'Desarrollador y diseñador web frontend con conocimientos de backend en búsqueda de nuevos retos y oportunidades de crecimiento. Actualmente trabajo por mi cuenta (freelance) y estudio la carrera de Licenciatura en Sistemas en la Universidad Nacional General Sarmiento.Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
